### ISSUE TITLE
Full Stack projektin katselmointi

### ISSUE THREAD

**Issue by Kaltsoon** [ilkkamaksy/share-expenses-app#2]
# Katselmointi

Terve @ilkkamaksy! Tässä lyhyt katselmointi Full Stack kurssin projektistasi.

### Mitä tein?

- Rekisteröiydyin uutena käyttäjänä
- Lisäsin uuden ryhmän parilla henkilöllä
- Muokkasin ryhmän nimeä
- Lisäsin kuluja ja muokkasin niitä
- Katsoin ryhmäni kuluja
- Kirjauduin ulos

### Kokemus

- Sovelluksella on todella tyylikäs ja selkeä käyttöliittymä, loistavaa työtä! 🥇
- Automaattinen sisäänkirjautuminen rekisteröitymisen jälkeen on todelle kätevää
- En löydä sovelluksen käytettävyydestä oikeastaan mitään moitittavaa, kaikki toiminnot on toteutettu erittäin huolellisesti. Todella amattimaista jälkeä!

## Koodi

- Frontend-puolen koodi on selkeästi organisoitua, hyvä!
- Kattavan oloista yksikkötestausta, hienoa!
- API-kutsuihin liittyvät operaatiot tuottavat Reduxin kanssa usein jonkin verran toisteellista boilerplate-koodia. [React Query](https://react-query.tanstack.com/) kirjaston avulla API-kutsut voi helposti abstraktoida yksinkertaisiksi hookeiksi
- Lomakkeiden tilanhallintaan ei välttämättä kannata toteuttaa itse Reduxilla. Lomakkeiden tilan ei usein tarvitse olla globaalia, jolloin Reduxin käyttö ei usein ole edes tarpeen. [Formik](https://jaredpalmer.com/formik)-kirjasto on eräs tähän käyttötarkoitukseen sopiva kirjasto
- Reduxin actioneiden typet kannattaa tallentaa `const`-tyyppisiin muuttujiin ja käyttää niiden arvoja sen sijaan, että käyttää niitä merkkijonomuotoisena. Tämä ehkäisee kirjoitusvirheistä syntyviä bugeja ja helpottaa refaktorointia. Mallia voi katsoa Reduxin [dokumentaatiosta](https://redux.js.org/basics/actions)
- Syvien tietorakenteiden immutable päivittäminen Reduxin reducereissa puhtaalla JavaScriptilla on melko työlästä. [Immer](https://www.npmjs.com/package/immer)-kirjasto helpottaa tätä huomattavasti
- [Redux Toolkit](https://redux-toolkit.js.org/) tarjoaa todella hyviä työkaluja Reduxin käyttöön. Esim. [createReducer](https://redux-toolkit.js.org/usage/usage-with-typescript#createreducer)-funktio vähentää reducerien boilerplate koodia huomattavasti. Se käyttää sisäisesti Immer-kirjastoa, joten myös tilan päivittäminen helpottuu
- [Button](https://github.com/ilkkamaksy/share-expenses-app/blob/master/react-native-frontend/components/forms/EditAccount.js#L81)-komponentin kanssa on monessa paikkaa toisteellisia propseja, kuten `color` ja `labelStyle`. Tässä tilanteessa kannattaisi toteuttaa oma `Button` komponentti, joka asettaa nämä propsit ja käyttää sitä sen sijaan, että käyttää suoraan React Native Paper -kirjaston komponenttia. React Native Paperilla tarjoaa myös mahdollisuuden [teeman konfigurointiin](https://callstack.github.io/react-native-paper/theming.html)
- Myös backend-puolen koodi on selkeästi organisoitua, hienoa!
- GraphQL-skeeman resolverit ja tyyppimäärittelyt on eriytetty siisti omiin tiedostoihinsa
- Datan "innokas" lataaminen ([eager loading](https://stackoverflow.com/questions/1299374/what-is-eager-loading)) ei ole GraphQL ideaologian mukaista. Vain se data, joka on kyselyssä määritelty tulisi hakea. Tämä tarkoittaa sitä, että [Model.populate](https://github.com/ilkkamaksy/share-expenses-app/blob/master/backend/schemas/invitation.js#L27)-metodeja ei kannattaisi queryissa kutsua. Toteuta tässä tilanteessa sen sijaan `Invitation` tyypille resolveri `group`-kentälle, joka hakee invitationin groupin. N+1-ongelman ratkaisemiseksi voi käyttää [DataLoader](https://www.npmjs.com/package/dataloader)-kirjastoa

## Kokonaisuus

Hyödyllinen sovellus, jossa on erittäin tyylikäs käyttöliittymä ja jonka käytettävyys on mintissä. Koodi on kaikilta osin hyvin organisoitua ja pääosin selkeää, mutta myös pientä refaktoroinnin tarvetta löytyy.

**Comment by ilkkamaksy** [comment]
Iso kiitos Kalle palautteesta! Nämä ovat todella hyviä neuvoja, jotka tulevat tarpeeseen. Mahtavaa!
